apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-command
spec:
  selector:
    matchLabels:
      app: demo-command
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demo-command
    spec:
      restartPolicy: Always
      containers:
      - name: demo-command
        image: demo-command:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /userap/application.yml
          subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: demo-config

---
apiVersion: v1
kind: Service
metadata:
  name: demo-command-np-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
  selector:
    app: demo-command